name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "huadaocredit"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.huadaocredit", custom_domain = true },
  { pattern = "quay.huadaocredit", custom_domain = true },
  { pattern = "gcr.huadaocredit", custom_domain = true },
  { pattern = "k8s-gcr.huadaocredit", custom_domain = true },
  { pattern = "k8s.huadaocredit", custom_domain = true },
  { pattern = "ghcr.huadaocredit", custom_domain = true },
  { pattern = "cloudsmith.huadaocredit", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.huadaocredit", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
